### ISSUE TITLE
Ability to read WAV file by chunks

### ISSUE THREAD

**Issue by fesor** [d-gamedev-team/wave-d#4]
As I understand, this implementation does all decoding process (file loading, decoding) in-memory only.

For example, I have very big WAV files (each of them >=1Gb). For example my program should get several files like this one, make some computation with PCM and write results into single WAV file.

Is there any chance that reading files by chunks (possible, decode an stream?) will be available in future?

**Comment by p0nce** [comment]
The Future has arrived => https://github.com/AuburnSounds/audio-formats
